FROM apache/airflow:2.9.2

USER root

# Установка Java и системных зависимостей
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-11-jdk \
        curl \
        gnupg \
        procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Установка PySpark и зависимостей
RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    findspark \
    py4j