FROM apache/airflow:2.9.2

USER root

# Установка Java и системных зависимостей для PySpark
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-11-jdk-headless \
        procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# PySpark будет установлен через _PIP_ADDITIONAL_REQUIREMENTS