FROM apache/airflow:2.9.2

USER root

# Установка Java и системных зависимостей для PySpark
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-11-jdk-headless \
        procps \
        curl \
        gnupg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Настройка JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow

# Установка PySpark и зависимостей
RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    findspark